# Generated by Django 2.2.1 on 2019-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='dificuldade',
            field=models.IntegerField(default=1),
        ),
    ]
